# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: Issue Duplicator
description: Duplicate an issue with labels, assignees, milestone, and GitHub project custom fields
author: Masaya Nakamura (@mashabow)

inputs:
  github-token:
    description: A GitHub personal access token with write access to the repo and the project
    required: true
  targetRepositories:
    description: 'Repository to which generated issue is copied. format: $OWNER/$REPO_NAME'
    required: true
  keyword:
    description: 'Keyword to trigger this action. The action is executed in the case of lowercased issue comment matched with lowercased keyword.'
    default: '/copy'

runs:
  using: node16
  main: dist/index.js

branding:
  color: green
  icon: copy
